const selectOptions = [
  {
    label: "Profile Update",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "BELUM UPDATE", label: "BELUM UPDATE" },
      { value: "SUDAH UPDATE", label: "SUDAH UPDATE" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Follow Up",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "BELUM", label: "BELUM" },
      { value: "FU1", label: "FU1" },
      { value: "FU2", label: "FU2" },
      { value: "FU3", label: "FU3" },
      { value: "FU4", label: "FU4" },
      { value: "FU5", label: "FU5" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Metode",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "WA", label: "WA" },
      { value: "CALL", label: "CALL" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Hasil FU",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "HOT", label: "HOT" },
      { value: "WARM", label: "WARM" },
      { value: "COLD", label: "COLD" },
      { value: "DEAL", label: "DEAL" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Dealer",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "SENTRAL YAMAHA MEDAN", label: "SENTRAL YAMAHA MEDAN" },
      { value: "PT. ALFA SCORPII - SETIA BUDI", label: "PT. ALFA SCORPII - SETIA BUDI" },
      { value: "PT; ALFA SCORPII - AR HAKIM", label: "PT; ALFA SCORPII - AR HAKIM" },
      { value: "PT; ALFA SCORPII - BILAL", label: "PT; ALFA SCORPII - BILAL" },
      { value: "PT; ALFA SCORPII - MARELAN", label: "PT; ALFA SCORPII - MARELAN" },
      { value: "PT; ALFA SCORPII - DELI TUA", label: "PT; ALFA SCORPII - DELI TUA" },
      { value: "PT; ALFA SCORPII - KAPTEN MUSLIM", label: "PT; ALFA SCORPII - KAPTEN MUSLIM" },
      { value: "PT; ALFA SCORPII - KATAMSO", label: "PT; ALFA SCORPII - KATAMSO" },
      { value: "PT; ALFA SCORPII - SM RAJA", label: "PT; ALFA SCORPII - SM RAJA" },
      { value: "PT; ALFA SCORPII - BINJAI", label: "PT; ALFA SCORPII - BINJAI" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Produk Yang Diminati",
    options: [{ value: "SEMUA", label: "SEMUA" }],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Area",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "MEDAN", label: "MEDAN" },
      { value: "SUMUT", label: "SUMUT" },
      { value: "ACEH", label: "ACEH" },
      { value: "PEKANBARU", label: "PEKANBARU" },
      { value: "RIAU", label: "RIAU" },
      { value: "KEP. RIAU", label: "KEP. RIAU" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Agama",
    options: [
      { value: "SEMUA", label: "SEMUA" },
      { value: "BUDDHA", label: "BUDDHA" },
      { value: "HINDU", label: "HINDU" },
      { value: "ISLAM", label: "ISLAM" },
      { value: "KATOLIK", label: "KATOLIK" },
      { value: "KRISTEN PROTESTAN", label: "KRISTEN PROTESTAN" },
      { value: "KONGHUCU", label: "KONGHUCU" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Pekerjaan",
    options: [
      { label: "SEMUA", value: "SEMUA" },
      { label: "Pegawai Negeri", value: "Pegawai Negeri" },
      { label: "Karyawan Swasta", value: "Karyawan Swasta" },
      { label: "Ibu Rumah Tangga", value: "Ibu Rumah Tangga" },
      { label: "Profesional", value: "Profesional" },
      { label: "Lain-lain", value: "aLin-lain" },
      { label: "Pelajar", value: "Pelajar" },
      { label: "TNI / Polri", value: "TNI / Polri" },
      { label: "Wiraswasta", value: "Wiraswasta" },
      { label: "Petani/Nelayan", value: "Petani/Nelayan" },
      { label: "Buruh", value: "Buruh" },
      { label: "Karyawan BUMN", value: "Karyawan BUMN" },
      { label: "Pelajar/Mahasiswa", value: "Pelajar/Mahasiswa" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Penghasilan",
    options: [
      { label: "SEMUA", value: "SEMUA" },
      { label: "Rp. 1.000.001", value: "1000001" },
      { label: "Rp. 2.000.001", value: "2000001" },
      { label: "Rp. 3.000.001", value: "3000001" },
      { label: "Rp. 4.000.001", value: "4000001" },
      { label: "Rp. 5.000.001", value: "5000001" },
      { label: "Rp. 6.000.001", value: "6000001" },
      { label: "Rp. 7.000.001", value: "7000001" },
      { label: "Rp. 1", value: "1" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
  {
    label: "Status Rumah",
    options: [
      { label: "SEMUA", value: "SEMUA" },
      { label: "MILIK SENDIRI", value: "MILIK SENDIRI" },
      { label: "ORANG TUA", value: "ORANG TUA" },
      { label: "KOST", value: "KOST" },
      { label: "KONTRAK/SEWA", value: "KONTRAK/SEWA" },
      { label: "RUMAH DINAS", value: "RUMAH DINAS" },
      { label: "PINDAH", value: "PINDAH" },
    ],
    defaultValue: { value: "SEMUA", label: "SEMUA" },
  },
];

export default selectOptions;
